### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribtue 'amp'

### ISSUE THREAD

**Issue by sriharsha0806** [NVIDIA/PyProf#142]
I ran quick start instructions, I am getting AttributeError: module 'torch.cuda' has no attribute 'amp'

```python
import torch.cuda.profiler as profiler 
import pyprof 
pyprof.init()
```
for the last line, this is the output
```
Initializing NVTX monkey patches
/home/sri/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sri/PyProf/pyprof/nvtx/nvmarker.py", line 695, in init
    patch_model_configs()
  File "/home/sri/PyProf/pyprof/nvtx/nvmarker.py", line 663, in patch_model_configs
    patch_never_call_with_args(torch.cuda.amp, "autocast", "amp_enabled", {"enabled": {True}})
AttributeError: module 'torch.cuda' has no attribute 'amp'
>>> pyprof.init()
Initializing NVTX monkey patches
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sri/PyProf/pyprof/nvtx/nvmarker.py", line 695, in init
    patch_model_configs()
  File "/home/sri/PyProf/pyprof/nvtx/nvmarker.py", line 663, in patch_model_configs
    patch_never_call_with_args(torch.cuda.amp, "autocast", "amp_enabled", {"enabled": {True}})
AttributeError: module 'torch.cuda' has no attribute 'amp'

```

**Comment by adityaiitb** [comment]
What version of PyTorch are you using? `torch.cuda.amp` has been available for a while. See [link](https://pytorch.org/docs/1.5.0/amp.html?highlight=torch%20cuda%20amp#module-torch.cuda.amp).

**Comment by sriharsha0806** [comment]
1.4.0

**Comment by adityaiitb** [comment]
PyTorch is a fast moving target and so we try to support only the newer / latest versions. If you are constrained to use 1.4, you can comment out the offending line 695 in nvmarker.py and then reinstall. Even if the installation and profiling work fine (step 1 of the tool), I am afraid the forward-backward kernel correlation (which happens in step 3 of the tool i.e. `prof.py`) might not work correctly because of changes introduced in version 1.5.

**Comment by pixar0407** [comment]
hello. 

I am facing the similar problem.

> ygkim@vlsi19:~/gpu_workload$ nvprof --csv --log-file ./outputs/vec_mat_1000_1000 --print-gpu-trace --profile-from-start off python vec_mat_mul.py --vec_dim 500 --mat_dim 300 --batch 1
> Initializing NVTX monkey patches
> /home/ygkim/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:102: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
>   warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> Traceback (most recent call last):
>   File "vec_mat_mul.py", line 5, in <module>
>     pyprof.init()
>   File "/home/ygkim/anaconda3/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 683, in init
>     patch_model_configs()
>   File "/home/ygkim/anaconda3/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 651, in patch_model_configs
>     patch_never_call_with_args(torch.cuda.amp, "autocast", "amp_enabled", {"enabled": {True}})
>   File "/home/ygkim/anaconda3/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 598, in patch_never_call_with_args
>     old_fn = getattr(mod, fn_name)
> AttributeError: module 'torch.cuda.amp' has no attribute 'autocast'

i am currently using pytorch version 1.5.0
But, if i remove the 'Pyprof.init()' and use only profiler.start() and profiler.end(), it still gives me output result.
this is strange.

Any suggestion?

**Comment by adityaiitb** [comment]
Please do a git pull and reinstall. Make sure the branch is `main` (not master). Please see the announcement on the landing page.

Also please use a newer / latest PyTorch. The reason is that the forward-backward kernel correlation (which happens in step 3 of the tool i.e. `prof.py`) might not work correctly because of changes specific to the profiler inside PyTorch version 1.5. Those changes were fixed in later versions. Please let us know if you encounter any errors with a newer version.

>> But, if i remove the 'Pyprof.init()' and use only profiler.start() and profiler.end(), it still gives me output result containing lots of >> information like Duration(us), GridX, Y, Z, Register per thread, Static SMem Throughput etc.

Yes, this is expected. Pyprof annotates the code with lots of information, using NVTX markers, which is captured by `nvprof` / `nsys`. If you don't use Pyprof you will see the usual nvprof output.

**Comment by pixar0407** [comment]
Thank you for the quick reply.

Currently I pulled the latest version of 'pyprof' from github and upgraded my pytorch version by typing ('pip install --upgrade torch torchvision').

Now, i am on the 'torch-1.7.1 torchvision-0.8.2'
And it works!

Also, this give me additionally NVTX results (which seems results of code line by line profile, i guess...). It seems good, though.

Thank you very much.

**Comment by pixar0407** [comment]
Hi, again.

If it is okay, then can i ask you one more question?
I want to use 'ncu'. 
So i typed 'ncu --profile-from-start off --set full python vec_mat_mul.py'

But i got error below.

> ygkim@vlsi19:~/gpu_workload$ ncu --profile-from-start off --set full python vec_mat_mul.py 
> Initializing NVTX monkey patches
> /home/ygkim/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:126: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
>   warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> Done with NVTX monkey patching
> ==PROF== Connected to process 10096 (/home/ygkim/anaconda3/bin/python3.8)
> ==ERROR== Error: Failed to prepare kernel for profiling
> ==ERROR== Failed to profile kernel "gemv2N_kernel" in process 10096
> torch.Size([1, 1, 1000])
> torch.Size([1, 1000, 1000])
> torch.Size([1, 1, 1000])
> ==PROF== Disconnected from process 10096
> ==ERROR== An error occurred while trying to profile.
> ==WARNING== No kernels were profiled.
> ==WARNING== Profiling kernels launched by child processes requires the --target-processes all option.

It seems ncu cannot prepare the kernel for profiling.
I am not sure I used this correctly.

I updated your 'Pyprof' and i am using NVIDIA 2080TI, python version is 3.8.0.
Is  there any suggestion?

Thank you.

**Comment by pixar0407** [comment]
> Please see [this](https://github.com/NVIDIA/PyProf/blob/main/docs/profile.rst#enable-profiler-in-pytorch-network) for detailed instructions on using Pyprof.
> 
> Currently it appears you are using `--csv`. If you save the output to a `.nvvp` file (which is a sqlite3 database), and then use the `parse` and `prof` scripts you will get very rich information.

Okay, i will try right now.

**Comment by adityaiitb** [comment]
I think you should use `nsys`. For example,

```
$ nsys profile
    -f true                     # Overwrite existing files
    -o net                         # Create net.qdrep (used by Nsys viewer)
    -c cudaProfilerApi      # Optional argument required for profiler start/stop
    --stop-on-range-end true # Optional argument required for profiler start/stop
    --export sqlite          # Export net.sql (similar to NVProf)
    python net.py
```
See [this](https://github.com/NVIDIA/PyProf/blob/main/docs/profile.rst#profile-with-nsight-systems).

**Comment by pixar0407** [comment]
Good to have suggestion about the output file format.

I am currently trying to use .nvvp file as you suggested.
So, i did below as the link says.

> nvprof -f -o net.sql --profile-from-start off python vec_mat_mul.py --vec_dim 500 --mat_dim 300 --batch 1

And i got net.sql file. So, i did below.

> python -m pyprof.parse net.sql > net.dict
> python -m pyprof.prof --csv net.dict

And i got the output below.

> ygkim@vlsi19:~/gpu_workload$ python -m pyprof.prof --csv net.dict
> "Idx","Direction","Sub","Module","Op","Kernel","Params","Sil(ns)"
> "1","fprop","0","torch","bmm","gemv2N_kernel","B=1,M=300,N=1,K=500,fp32,","6721"

Is this what you had suggested?
Cause i am not familiar with .nvvp file foramt and i could not understand the 'then use the parse and prof scripts', I just want to make sure that i understand you fully to get rich information :)

**Comment by adityaiitb** [comment]
Yes. The output of NVprof (`net.sql`) can be opened in NVVP (Nvidia Visual Profiler) if you want to look at the data visually. That's why I mentioned nvvp. `net.nvvp == net.sql`, the file extension does not matter, its basically a sqlite3 database which you can also open using the sqlite3 cli.

By parse and prof I meant `pyprof.parse` and `pyprof.prof` which you used above.

Also see [this](https://github.com/NVIDIA/PyProf/blob/main/docs/profile.rst#run-the-prof-script) for how to better use `pyprof.prof`. You can choose which columns to print and/or a tabular format to better readability. There are almost 20 columns of output.

**Comment by pixar0407** [comment]
Okay.

By the way, 'look at the data visually'(what you said earlier) means that it shows 'graph(like, it has x axis and y axix etc)'? or a table (like, "Idx","Direction","Sub","Module","Op","Kernel","Params","Sil(ns)"
"1","fprop","0","torch","bmm","gemv2N_kernel","B=1,M=300,N=1,K=500,fp32,","6721")?

Because i am using Xshell4, I can not get any visual outputs.
I am once told that Xshell can not plot any visual data...

So, I am worry i am missing something.
i guess Visual means something like below.

![nsight-systems-profiler-visualization-2-1536x958](https://user-images.githubusercontent.com/26530798/108588293-adec4600-739b-11eb-8e35-0fe9eea6d443.png)

As this [link(link)](https://developer.nvidia.com/blog/profiling-and-optimizing-deep-neural-networks-with-dlprof-and-pyprof/) says (the picture above is coming from this link), 

> The qdrep files are obtained when training with the profiler call is completed.

Yes! i got that file (net2.qdrep) by doing this line below.

> ygkim@vlsi19:~/gpu_workload$ nsys profile -f true -o net2 --export sqlite python vec_mat_mul.py

So i guess i am heading the right direction. But i think i don't know what i am doing right now...
Let me search this and study other material and come back to you soon.
