### ISSUE TITLE
cxxfilt error

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/PyProf#32]
Hi,
I have been trying to install pyprof and I am keep hitting the error caused by cxxfilt.

ERROR: Could not find a version that satisfies the requirement cxxfilt>=0.2.0 (from pyprof==3.2.0.dev0) (from versions: none)
ERROR: No matching distribution found for cxxfilt>=0.2.0 (from pyprof==3.2.0.dev0)

even though there are some variations in the error messages they are all cxxfilt based. 

things I tried:
1) building the docker image based on the file in the repo
2) git clone & install
3) trying to install cxxfilt manually 

any idea?

**Comment by ethem-kinginthenorth** [comment]
Interestingly, in a different machine I was able to build the docker image. I am not sure what is the difference between the machines though

**Comment by adityaiitb** [comment]
hi,

My suspicion is that the path or an environment variable (e.g. $HOME) is not set correctly inside the docker container. Can you do the following without using docker, so that we can identify where is the problem.

```
git clone https://github.com/NVIDIA/PyProf.git
cd PyProf
pip3 install . --user
```

This should install everything in `$HOME/.local/lib/python3.7/site-packages` and can be easily removed as well.

**Comment by ethem-kinginthenorth** [comment]
still didn't work in the container. Seems like in the container in that particular box, I am not getting it working - Maybe permission issues. 

Anyways, it works in a different machine and I am good. thanks. closing the issue.
